refactor
fac/sf-deployment-monitoring-action pull request #5
Opened 2023-08-02 09:38 UTC by cornet

- Refactor
- Need the 2nd to last event

2023-08-02 10:00 UTC, dancorne approved these changes
LGTM. I've added a suggested message if containers fail to boot, happy to reapprove if you wanna update that message. Technically it might not be _just_ the Sidekiq containers but they'll be the first detected -- will note that in the playbook.

2024-02-29 16:51 UTC, dancorne requested changes
Nice! Got a couple of questions...

2024-02-29 16:51 UTC, dancorne commented on lib/deployment/deployment.rb
> +      @status ||= @aws_client.describe_execution({ execution_arn: @execution_arn }).status
Doesn't `||=` mean `@status` will only be fetched once and so `status` will only ever return the status after the first `describe_execution` call?

2024-02-29 16:51 UTC, dancorne commented on lib/deployment/deployment.rb
> +      # The penultimate event holds the failure reason
Is this true? I see it's the previous behaviour but...
 - It looks like the case for Preflight Checks as that gets caught and sent to `Fail`
 - For the CodeDeploy trigger state until the switchover state, it goes through the Rollback flow so it looks to me like the fourth state back will be the "error cause" state.

So I don't think this is a regression, but I'm also not sure it's right...

2024-02-29 16:51 UTC, dancorne commented on spec/app_spec.rb
> +    it 'ouptuts that it failed' do
```suggestion
    it 'outputs that it failed' do
```

2024-02-29 16:51 UTC, dancorne commented on spec/app_spec.rb
> +    it 'ouptuts that it failed' do
```suggestion
    it 'outputs that it failed' do
```

2024-02-29 16:51 UTC, dancorne commented on spec/lambda_function_failed_spec.rb
> +  context 'some other pre-flight check failed' do
It might be worth handling an out-of-hours failure which happened recently here for example: https://github.com/fac/freeagent-pdf-service/actions/runs/8098826387/job/22133294298

Not a hard requirement for this PR though.

2024-02-29 17:04 UTC, cornet commented on lib/deployment/deployment.rb
> +      # The penultimate event holds the failure reason
The last execution state is "Execution Failed" which doesn't hold any information which  I believe is why we want the penultimate event

<img width="1282" alt="image" src="https://github.com/fac/sf-deployment-monitoring-action/assets/142294/8ee7ab00-1c5e-437a-b744-3f7c2a53f623">

2024-02-29 17:09 UTC, cornet commented on lib/deployment/deployment.rb
> +      # The penultimate event holds the failure reason
oh sorry, that doesn't answer your question.

I believe any error gets passed through all the events...

If we take this failure from sandbox

<img width="536" alt="image" src="https://github.com/fac/sf-deployment-monitoring-action/assets/142294/3e170cde-10a9-4135-b57b-73c04d5c0cc4">


Then the penultimate state contains the error passed down from the Lambda function:

<img width="1361" alt="image" src="https://github.com/fac/sf-deployment-monitoring-action/assets/142294/061d48aa-0655-4247-a775-588805c7ea74">

2024-02-29 17:09 UTC, cornet commented on lib/deployment/deployment.rb
> +      # The penultimate event holds the failure reason
Here is the link to the execution in fa-app-sandbox https://eu-west-1.console.aws.amazon.com/states/home?region=eu-west-1#/v2/executions/details/arn:aws:states:eu-west-1:994904732622:execution:freeagent-deployments:9b402ec4-70f5-49ed-a3c7-aa6076178edb

2024-02-29 17:10 UTC, cornet commented on spec/lambda_function_failed_spec.rb
> +  context 'some other pre-flight check failed' do
I intend to handle all of them but don't want to make any behaviour changes until after the refactor

2024-02-29 17:19 UTC, dancorne commented on spec/lambda_function_failed_spec.rb
> +  context 'some other pre-flight check failed' do
Thought so 👍

2024-02-29 17:20 UTC, dancorne commented on lib/deployment/deployment.rb
> +      # The penultimate event holds the failure reason
Ah I was blanking on the behaviour. This isn't the "problematic event", it's the literal "fail event" which can be used to get the state 👍

2024-03-01 10:16 UTC, dancorne requested changes

2024-03-01 10:16 UTC, dancorne commented on spec/app_spec.rb
> +      $stdout = StringIO.new
Does this need to be global? I'm not sure how that affects behaviour if the tests run in parallel as it's a global variable declared three times: do each of the tests in here share a stdout so you could be testing output from other tests?

2024-03-01 10:16 UTC, dancorne commented on Gemfile
> +  gem 'rspec-mocks'
As mentioned in standup, these could go in a development group (I'm guessing nokogiri is only used for tests anyway? Not sure where it gets used tbh).

2024-03-01 11:21 UTC, cornet commented on spec/app_spec.rb
> +      $stdout = StringIO.new
`$stdout` is a pre defined global variable and is where stdout is sent. We set it to a new stringio object so we can read it back at the end of the test and check it output what we wanted.

I've not hit any issues with multiple test overlapping but i guess it is a possibility. 

This particular test file was only really created to make sure the behaviour didn't change. Now that we have the other tests I'll likely remove it in a separate PR

2024-03-01 12:07 UTC, dancorne commented on spec/app_spec.rb
> +      $stdout = StringIO.new
Cool, thanks 👍

2024-03-01 12:11 UTC, dancorne approved these changes

2024-03-01 14:44 UTC, dancorne approved these changes
Good catch 👍

2024-03-01 14:45 UTC, merged